name: Run Unit Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Lấy mã nguồn
      uses: actions/checkout@v3

    - name: Cài Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cài pytest
      run: pip install pytest

    - name: Chạy kiểm thử
      run: pytest
